[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.8.0"
itertools = "0.10.3"
regex = "1"
lazy_static = "1.4.0"
